github-clone now works with both http and ssh urls

diff --git a/bin/github-clone b/bin/github-clone
--- a/bin/github-clone
+++ b/bin/github-clone
@@ -1,9 +1,17 @@
-#!/usr/bin/env sh
+#!/usr/bin/env zsh
 
 source "$(dirname "$0")/script-helpers"
 
-DEST="$HOME/src/github.com/$1"
-REPO_URL="https://github.com/$1.git"
+if ! [[ "$1" =~ ([^\/:]+)\/([^\/.]+)(.git)?$ ]]; then
+	error "$1 unable to extract owner and repo"
+fi
+
+GITHUB_OWNER="${match[1]}"
+GITHUB_REPO_NAME="${match[2]}"
+GITHUB_NAME_WITH_OWNER="${GITHUB_OWNER}/${GITHUB_REPO_NAME}"
+
+DEST="$HOME/src/github.com/$GITHUB_NAME_WITH_OWNER"
+REPO_URL="git@github.com:$GITHUB_NAME_WITH_OWNER.git"
 
 if [[ ! -d "$DEST" ]]; then
 	msg "Cloning $REPO_URL to $DEST"
